### ISSUE TITLE
Maintaining this package

### ISSUE THREAD

**Issue by anmolitor** [eriktim/protoc-gen-elm#18]
Hi there, 
I am currently developing an Haskell/Elm/Protobuf Web Application as a side project and I had a lot of issues with the generated code (many of the already open issues and some further ones). The fact that 3 years passed since this repository last got updated led me to fork the repository and adjust the code such that it generated correct code for my scenario. 

Do you want me to make a big pull request or just publish the fork as a seperate npm package? Obviously, I would credit you for this already pretty awesome plugin. I've not worked open source so far, so I would appreciate any advice.

Thanks,
Andreas

**Comment by eriktim** [comment]
Hi Andreas, sorry for being inactive on this project. I'm using Elm nor ProtoBuf these days so the enthusiasm kinda slipped away. You could make a big or smaller PRs but that'll get you in the same position in the future I guess. What I would suggest is that you fork the project and I add you to the npm package as a maintainer. We could then gradually migrate it to your repository, which I can help you with if needed.

**Comment by anmolitor** [comment]
Thanks for the response! Once I am satisfied with the feature set of my fork, I'll come back here :)

**Comment by anmolitor** [comment]
Hi Erik,
I finished my work on the fork for now and published the package temporarily under https://www.npmjs.com/package/protoc-gen-elm-fork. I then installed it in my Haskell/Elm Project and so far it worked well :)

So should we start with the migration then?

**Comment by okkero** [comment]
Any updates on this? The fork by @andreasewering seems to have fixed a lot of the issues with this one, so a migration/merge seems justified if that's still on the table.

**Comment by okkero** [comment]
I'm using the fork as my go-to for now. I would also like to contribute, but I was unable to open an issue on the fork, so I'm not sure where to go. It doesn't handle decoding mutually recursive data structures, it seems. I think that should be possible by using `Protobuf.Decode.lazy`, but I guess the generator just doesn't detect recursions.

Again, I would love an update on the migration. Thank you.

**Comment by eriktim** [comment]
Thanks for the reminder @okkero.
@andreasewering I've added you as an admin. Can you try to update the package?

**Comment by anmolitor** [comment]
Worked. I released a version 2.0.0 :)

**Comment by anmolitor** [comment]
@okkero I tried to detatch the fork using the github assistent, so that issues can be created in my repository. It looked like it should work. I'm on holiday for the next 10 days, afterwards I will gladly look at your issue regarding recursive data structures.

**Comment by okkero** [comment]
Nice!
@andreasewering I can still not create issues in your repository. It might be that the feature is disabled.

**Comment by anmolitor** [comment]
@okkero Correct. It should work now, I see an Issues Tab when visiting my repository now
